# Generated by Django 5.2.10 on 2026-02-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('event_type', models.CharField(choices=[('deadline', 'Deadline'), ('stage_start', 'Début de stage'), ('stage_end', 'Fin de stage'), ('meeting', 'Réunion'), ('interview', 'Entretien'), ('conference', 'Conférence'), ('training', 'Formation'), ('other', 'Autre')], default='other', max_length=20, verbose_name="Type d'événement")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('is_public', models.BooleanField(default=False, help_text='Visible par tous les utilisateurs', verbose_name='Public')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
