# Generated by Django 5.2.10 on 2026-02-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('partner_type', models.CharField(choices=[('company', 'Entreprise'), ('school', 'École/Université'), ('institution', 'Institution'), ('association', 'Association'), ('service', 'Service Public'), ('other', 'Autre')], default='company', max_length=20, verbose_name='Type de partenaire')),
                ('category', models.CharField(choices=[('finance', 'Financement'), ('housing', 'Logement'), ('transport', 'Transport'), ('admin', 'Administratif'), ('health', 'Santé'), ('culture', 'Culture'), ('sport', 'Sport'), ('food', 'Restauration'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Description courte')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('address', models.CharField(max_length=300, verbose_name='Adresse')),
                ('city', models.CharField(default='Cayenne', max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Ex: 4.937200', max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Ex: -52.326000', max_digits=9, verbose_name='Longitude')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Logo')),
                ('is_verified', models.BooleanField(default=False, help_text="Partenaire vérifié par l'équipe", verbose_name='Vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['name'],
            },
        ),
    ]
