# Generated by Django 5.2.10 on 2026-02-07 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Emoji ou classe CSS', max_length=50, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de ressource',
                'verbose_name_plural': 'Catégories de ressources',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'Document PDF'), ('video', 'Vidéo'), ('link', 'Lien externe'), ('article', 'Article'), ('template', 'Modèle/Template'), ('guide', 'Guide'), ('tool', 'Outil')], max_length=20, verbose_name='Type de ressource')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(blank=True, help_text='Pour les articles et guides', verbose_name='Contenu')),
                ('file', models.FileField(blank=True, help_text='PDF, documents, etc.', null=True, upload_to='hub/resources/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, help_text='Pour les liens externes et vidéos', verbose_name='URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hub/thumbnails/', verbose_name='Miniature')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=200, verbose_name='Tags')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Téléchargements')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='hub.resourcecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('objectives', models.TextField(help_text='Un objectif par ligne', verbose_name='Objectifs')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], default='beginner', max_length=20, verbose_name='Niveau')),
                ('duration_hours', models.PositiveIntegerField(help_text='Durée estimée en heures', verbose_name='Durée (heures)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hub/trainings/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, etc.', verbose_name='URL vidéo')),
                ('instructor_name', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'instructeur")),
                ('instructor_bio', models.TextField(blank=True, verbose_name="Bio de l'instructeur")),
                ('enrollments_count', models.PositiveIntegerField(default=0, verbose_name='Inscriptions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='trainings', to='hub.resource', verbose_name='Ressources associées')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-created_at'],
            },
        ),
    ]
