# Generated by Django 5.2.11 on 2026-02-08 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_housingapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolingoffer',
            name='driver',
            field=models.ForeignKey(help_text='Seuls les chauffeurs vérifiés peuvent proposer du covoiturage', on_delete=django.db.models.deletion.CASCADE, related_name='carpooling_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housingoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix maximum: 300€/mois pour protéger les étudiants contre la vie chère', max_digits=10),
        ),
    ]
