# Generated by Django 5.2.11 on 2026-02-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_carpoolingoffer_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolingoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='housingoffer',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
