# Generated by Django 5.2.11 on 2026-02-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_CARD', "Carte d'identité"), ('PASSPORT', 'Passeport'), ('PROPERTY_PROOF', 'Justificatif de propriété'), ('ADDRESS_PROOF', 'Justificatif de domicile'), ('DRIVER_LICENSE', 'Permis de conduire'), ('VEHICLE_REGISTRATION', 'Carte grise'), ('INSURANCE', "Attestation d'assurance"), ('CRIMINAL_RECORD', 'Casier judiciaire')], max_length=30)),
                ('file', models.FileField(upload_to='verification_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de Vérification',
                'verbose_name_plural': 'Documents de Vérification',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
