# Generated by Django 5.2.11 on 2026-02-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['status'], name='verification_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['document_type'], name='verification_type_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['-submitted_at'], name='verification_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['expiry_date'], name='verification_expiry_idx'),
        ),
    ]
