# Generated by Django 5.2.11 on 2026-02-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('autonomy', models.BooleanField(default=False)),
                ('teamwork', models.BooleanField(default=False)),
                ('rigor', models.BooleanField(default=False)),
                ('creativity', models.BooleanField(default=False)),
                ('punctuality', models.BooleanField(default=False)),
                ('skills_validated', models.JSONField(default=list)),
                ('comment', models.TextField()),
                ('recommended_domains', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_given', to='users.companyprofile')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='internships.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_received', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'student', 'internship')},
            },
        ),
    ]
