# Generated by Django 5.2.11 on 2026-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='internrecommendation',
            index=models.Index(fields=['rating'], name='rec_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='internrecommendation',
            index=models.Index(fields=['is_public'], name='rec_public_idx'),
        ),
        migrations.AddIndex(
            model_name='internrecommendation',
            index=models.Index(fields=['is_featured'], name='rec_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='internrecommendation',
            index=models.Index(fields=['-created_at'], name='rec_created_idx'),
        ),
    ]
