# Generated by Django 5.2.11 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_description',
            field=models.TextField(blank=True, verbose_name="Description de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, verbose_name="Taille de l'entreprise"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, verbose_name="Domaine d'études"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'obtention du diplôme"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages',
            field=models.TextField(blank=True, help_text='Langues parlées', verbose_name='Langues'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for_internship',
            field=models.BooleanField(default=True, verbose_name='Recherche un stage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Portfolio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='École/Université'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='siret',
            field=models.CharField(blank=True, max_length=20, verbose_name='SIRET'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, help_text='Compétences séparées par des virgules', verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
