# Generated by Django 5.2.11 on 2026-02-08 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise'), ('admin', 'Admin'), ('recruiter', 'Recruteur'), ('school', 'École/Université'), ('training_center', 'Centre de Formation'), ('landlord', 'Particulier/Propriétaire'), ('driver', 'Chauffeur/Taxi'), ('partner', 'Partenaire Institutionnel')], default='student', max_length=20),
        ),
    ]
