# Generated by Django 5.2.11 on 2026-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='is_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_verified'], name='user_type_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['looking_for_internship'], name='looking_internship_idx'),
        ),
    ]
