# Generated by Django 5.2.11 on 2026-02-08 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_user_type_idx_customuser_is_verified_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('subjects', models.TextField(blank=True, help_text='Séparées par des virgules', verbose_name='Matières enseignées')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(limit_choices_to={'user_type': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('user', 'school')},
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='Ex: L3 AES, BTS 2ème année', max_length=100, verbose_name='Classe')),
                ('program', models.CharField(help_text='Ex: Administration Économique et Sociale', max_length=200, verbose_name='Filière')),
                ('academic_year', models.CharField(help_text='Ex: 2025-2026', max_length=20, verbose_name='Année scolaire')),
                ('student_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro étudiant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(limit_choices_to={'user_type': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='school_enrollments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.teacher', verbose_name='Enseignant référent')),
            ],
            options={
                'verbose_name': 'Inscription Élève',
                'verbose_name_plural': 'Inscriptions Élèves',
                'ordering': ['-enrollment_date'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='enrollment_school_idx'), models.Index(fields=['teacher', 'is_active'], name='enrollment_teacher_idx')],
                'unique_together': {('student', 'school', 'academic_year')},
            },
        ),
    ]
