# Generated by Django 5.2.11 on 2026-02-08 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', "Pièce d'identité"), ('property_proof', 'Justificatif de propriété'), ('home_insurance', 'Assurance habitation'), ('driver_license', 'Permis de conduire'), ('vehicle_registration', 'Carte grise'), ('vehicle_insurance', 'Assurance véhicule'), ('internship_convention', 'Convention de stage'), ('contract', 'Contrat'), ('administrative_doc', 'Document administratif'), ('cv', 'CV'), ('cover_letter', 'Lettre de motivation'), ('certificate', 'Attestation'), ('signed_convention', 'Convention signée'), ('other', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], default='pending', max_length=20, verbose_name='Statut')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('expiry_date', models.DateField(blank=True, help_text="Pour les documents avec date d'expiration (permis, assurance, etc.)", null=True, verbose_name="Date d'expiration")),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_documents_verified', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Document utilisateur',
                'verbose_name_plural': 'Documents utilisateurs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='doc_user_status_idx'), models.Index(fields=['document_type'], name='doc_type_idx'), models.Index(fields=['expiry_date'], name='doc_expiry_idx')],
            },
        ),
    ]
