# Generated by Django 5.2.11 on 2026-02-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_note',
            field=models.TextField(blank=True, help_text="Commentaire de l'admin sur le statut du dossier", verbose_name='Note de vérification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('incomplete', 'Dossier incomplet'), ('under_review', "En cours d'examen"), ('verified', 'Vérifié'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20, verbose_name='Statut de vérification'),
        ),
    ]
