# Generated by Django 5.2.11 on 2026-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Pièce d'identité"), ('address_proof', 'Justificatif de domicile'), ('property_proof', 'Justificatif de propriété'), ('home_insurance', 'Assurance habitation'), ('driver_license', 'Permis de conduire'), ('vehicle_registration', 'Carte grise'), ('vehicle_insurance', 'Assurance véhicule'), ('kbis_siret', 'Extrait Kbis/SIRET'), ('representative_id', "Pièce d'identité du représentant"), ('accreditation', 'Agrément/Accréditation'), ('internship_convention', 'Convention de stage'), ('contract', 'Contrat'), ('administrative_doc', 'Document administratif'), ('partnership_proof', 'Document justificatif du partenariat'), ('cv', 'CV'), ('cover_letter', 'Lettre de motivation'), ('certificate', 'Attestation'), ('signed_convention', 'Convention signée'), ('other', 'Autre')], max_length=50, verbose_name='Type de document'),
        ),
    ]
