# Generated by Django 5.2.11 on 2026-02-08 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('programs', models.JSONField(default=list)),
                ('active_conventions', models.IntegerField(default=0)),
                ('total_conventions_managed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('office_hours', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_managers', to='users.schoolprofile')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de Stage',
                'verbose_name_plural': 'Responsables de Stage',
            },
        ),
        migrations.CreateModel(
            name='InternshipCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('program_level', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_students', models.IntegerField()),
                ('skills_sought', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_visible_to_companies', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_calendars', to='users.schoolprofile')),
                ('program_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_calendars', to='calendars.programmanager')),
            ],
            options={
                'verbose_name': 'Calendrier de Stage',
                'verbose_name_plural': 'Calendriers de Stages',
                'ordering': ['start_date'],
            },
        ),
    ]
