# Generated by Django 5.2.11 on 2026-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='internshipcalendar',
            index=models.Index(fields=['is_published'], name='calendar_published_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipcalendar',
            index=models.Index(fields=['is_visible_to_companies'], name='calendar_visible_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipcalendar',
            index=models.Index(fields=['start_date'], name='calendar_start_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipcalendar',
            index=models.Index(fields=['program_level'], name='calendar_level_idx'),
        ),
    ]
