# Generated by Django 5.2.11 on 2026-02-08 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_companyprofile_driverprofile_landlordprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvolutionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('STUDYING', 'En études'), ('EMPLOYED', 'En emploi'), ('AVAILABLE', 'Disponible'), ('SEEKING', 'En recherche')], max_length=20)),
                ('evolution_history', models.JSONField(default=list)),
                ('notify_on_level_change', models.BooleanField(default=True)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_availability', models.BooleanField(default=True)),
                ('started_tracking_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_students', to='users.companyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_companies', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Suivi Évolution Étudiant',
                'verbose_name_plural': 'Suivis Évolution Étudiants',
                'unique_together': {('company', 'student')},
            },
        ),
    ]
