# Generated by Django 5.2.11 on 2026-02-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevolutiontracking',
            old_name='started_tracking_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentevolutiontracking',
            old_name='last_updated_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='studentevolutiontracking',
            name='company',
            field=models.ForeignKey(limit_choices_to={'user_type': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentevolutiontracking',
            name='current_level',
            field=models.CharField(choices=[('BEGINNER', 'Débutant'), ('INTERMEDIATE', 'Intermédiaire'), ('ADVANCED', 'Avancé'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentevolutiontracking',
            name='domain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentevolutiontracking',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('IN_INTERNSHIP', 'En stage'), ('EMPLOYED', 'En emploi'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentevolutiontracking',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
