# Generated by Django 5.2.11 on 2026-02-08 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_rename_started_tracking_at_studentevolutiontracking_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentevolutiontracking',
            index=models.Index(fields=['current_level'], name='tracking_level_idx'),
        ),
        migrations.AddIndex(
            model_name='studentevolutiontracking',
            index=models.Index(fields=['status'], name='tracking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentevolutiontracking',
            index=models.Index(fields=['-updated_at'], name='tracking_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='studentevolutiontracking',
            index=models.Index(fields=['company', 'student'], name='tracking_company_student_idx'),
        ),
    ]
