# Generated by Django 5.2.11 on 2026-02-08 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
        ('tracking', '0003_studentevolutiontracking_tracking_level_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('INTERRUPTED', 'Interrompu')], default='NOT_STARTED', max_length=20)),
                ('mid_term_evaluation', models.TextField(blank=True)),
                ('mid_term_evaluation_date', models.DateField(blank=True, null=True)),
                ('final_evaluation', models.TextField(blank=True)),
                ('final_evaluation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes internes de suivi')),
                ('convention_signed', models.BooleanField(default=False)),
                ('convention_file', models.FileField(blank=True, null=True, upload_to='conventions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackings', to='internships.internship')),
                ('school', models.ForeignKey(limit_choices_to={'user_type': 'school'}, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_internships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='internship_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de Stage',
                'verbose_name_plural': 'Suivis de Stages',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='int_track_status_idx'), models.Index(fields=['start_date'], name='int_track_start_idx'), models.Index(fields=['school', 'status'], name='int_track_school_idx')],
            },
        ),
    ]
