# Generated by Django 5.2.11 on 2026-02-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_internshiptracking'),
        ('users', '0006_teacher_studentschoolenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiptracking',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_internships', to='users.teacher', verbose_name='Enseignant référent'),
        ),
    ]
