# Generated by Django 5.2.11 on 2026-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_received', 'Candidature reçue'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature refusée'), ('new_internship', 'Nouvelle offre de stage'), ('message_received', 'Nouveau message'), ('document_submitted', 'Document soumis'), ('document_approved', 'Document approuvé'), ('document_rejected', 'Document rejeté'), ('profile_verified', 'Profil vérifié'), ('profile_rejected', 'Profil rejeté'), ('profile_suspended', 'Profil suspendu'), ('profile_incomplete', 'Dossier incomplet'), ('system', 'Notification système')], default='system', max_length=50),
        ),
    ]
